---
- name: Link letsencrypt certificate
  hosts: servers
  tasks:
    - name: make 2ip dir
      file: path=/etc/2ip state=directory

    - name: chmod for /etc/letsencrypt/archive/
      file:
        path: /etc/letsencrypt/archive/
        mode: 0755

    - name: chmod for /etc/letsencrypt/live/
      file:
        path: /etc/letsencrypt/live/
        mode: 0755

    - name: symlink for 2ip dir
      file:
        src: /etc/letsencrypt/live/{{ node_host }}/{{ item.path }}
        dest: /etc/2ip/{{ item.dest }}
        state: link
      with_items:
        - { path: 'fullchain.pem', dest: 'cert.pem' }
        - { path: 'privkey.pem', dest: 'key.pem' }