---
- name: Install packages
  hosts: servers
  user: root
  tasks:
    - name: Stop platform
      service:
        name: 2ip-speed.service
        state: stopped
        enabled: no
      failed_when: false
      
    - name: Install binaries
      unarchive:
        src: "https://github.com/bis-gmbh/2ip-speed/releases/download/v4/2ip.speed.linux.{{ansible_architecture}}.tar.gz"
        dest: "/usr/bin/"
        copy: no

    - name: Install service template
      template:
        src: templates/2ip-speed.service
        dest: /etc/systemd/system/2ip-speed.service
      notify:
        - reload systemctl

    - name: Start platform
      service: name=2ip-speed.service state=started enabled=yes

    - name: Check platform status
      command: systemctl is-active 2ip-speed.service
      register: service_status
      changed_when: false
      failed_when: service_status.stdout != "active"

  handlers:
    - name: reload systemctl
      command: systemctl daemon-reload
